version: "3.2"
networks: 
  optimaltech:
    ipam: 
      driver: default
      config: 
        - subnet: 172.20.0.0/16
services:
  frontend:
    container_name: frontend-service
    build: ./build/frontend
    ports:
      - '4000:3000'
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    command: sh -c "npm install && npm run dev"
    tty: true
    networks: 
      optimaltech:
        ipv4_address: 172.20.1.1

  backend:
    container_name: backend-service
    build: ./build/backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    networks: 
      optimaltech:
        ipv4_address: 172.20.1.2